#!/bin/bash
#
# a simple dmenu session script 
#
###

DMENU='dmenu -i -b -l 5 -fn "Sans-12"'
choice=$(echo -e "shutdown\nsuspend\nhibernate\nreboot\nkill x" | $DMENU)

case "$choice" in
  shutdown) systemctl poweroff
    ;;
  suspend) systemctl suspend
    ;;
  hibernate) systemctl hibernate
    ;;
  reboot) systemctl reboot
    ;;
  'kill x') i3-msg exit 
esac

exit 0
