#!/usr/bin/env bash
#
# a simple dmenu session script 
#
###

DMENU='dmenu -i -b -l 5 -fn "Sans-12"'
choice=$(echo -e "shutdown\nhybrid\nsuspend\nhibernate\nreboot\nkill x" | dmenu_i3_style -i -b -l 5)

case "$choice" in
  shutdown) systemctl poweroff
    ;;
  hybrid) systemctl hybrid-sleep
    ;;
  suspend) systemctl suspend
    ;;
  hibernate) systemctl hibernate
    ;;
  reboot) systemctl reboot
    ;;
  'kill x') i3-msg exit 
esac

exit 0
