#!/usr/bin/env bash
#
# Simple dmenu session script.
#
###

choice=$(echo -e "shutdown\nhybrid\nsuspend\nhibernate\nreboot\nkill x" | dmenu_i3_style -i -b -l 6)

case "$choice" in
  shutdown) systemctl poweroff
    ;;
  hybrid) systemctl hybrid-sleep
    ;;
  suspend) systemctl suspend
    ;;
  hibernate) systemctl hibernate
    ;;
  reboot) systemctl reboot
    ;;
  'kill x') i3-msg exit                # on a non-i3 system, try kill $(pgrep X)
    ;;
  *) exit 1
esac

exit 0
