#!/usr/bin/env bash
#
# uses find to list all matching files, then uses xdg-open to open with 
# default application
#
###

DMENU='dmenu_i3_style -i -b'

directory=$(cd ~; (echo -e '~/'; ls -d */) | $DMENU -p "Search Directory:")

if [ "${directory}" == '~/' ]; then
  search_path="${HOME}"
else
  search_path="$HOME/$directory"
fi

input=$($DMENU -p "Search Directory $search_path for:" <&-)

if [ "$input" != '' ]; then
  result=$(find -L $search_path -iname "*$input*" -not -path '*\/.*' | $DMENU -l 20 -p "Search Results:")
  if [ "$result" != '' ]; then
    xdg-open "$result"
  fi
fi
