#!/usr/bin/env bash
#
# launch binaries through dmenu, with the option to pin most used programs to
# the front of the search list.
# appending a "!" runs the command with sudo permissions
# appending a ";" runs the command in a terminal
#
###

DMENU='dmenu_i3_style -i -b'
TERM="urxvt -e $SHELL -ic"

DMENU_PATH=$(cat ~/.cache/dmenu_run)

CACHE="$HOME/.cache/dmenu_freq"
touch "${CACHE}"
MOST_USED=$(sort "${CACHE}" | uniq | sed '/^$/d')

run=$((echo "${MOST_USED}"; echo "${DMENU_PATH}") | $DMENU)

# parse ; and !
case $run in
  *\!\;|*\;\!)
    com="${run:0:-2}"
    exec="$TERM 'sudo $com && $SHELL'"
    ;;
  *\!)   
    com="${run:0:-1}"
    exec="gksudo $com"
    ;;
  *\;) 
    com="${run:0:-1}"
    exec="$TERM '$com && $SHELL'"
    ;;
  *)
    com="$run"
    exec="$com"
    ;;
esac

# remove any arguments, so that only the base command is used
base_com=$(echo "${com}" | awk '{print $1}')

# if command exists, run it
if (type "${base_com}" > /dev/null 2>&1); then
  # if it isn't on the most used list, ask
  if ! (echo "${MOST_USED}" | grep -Fxq "${base_com}"); then
    save=$(echo | $DMENU -p 'Save to most used? (y/N)')
    if [[ "${save}" == "y" ]]; then
      # add to most used programs
      (echo "${base_com}"; echo "$MOST_USED") > "${CACHE}.tmp" && mv "${CACHE}.tmp" "${CACHE}"
    fi
  fi
  eval "$exec &"
else
  echo "Unknown command $base_com"
  exit 1
fi

exit 0
